### PR TITLE
Updates for CFWheels 1.3.3 Compatibility

### PR DESCRIPTION
**Pull request by jkeczan**
This has been tested on IE/Mac OSX. Linux untested

Tested For 
CF 11
Apache 2.4
MSSQL 2012/2014

### CODE REVIEW

**Comment by tdm00** [comment]
I'm not doing active ColdFusion / CFWheels development so I don't feel like I'm the best person to test / verify these code changes. Would you be willing to have write access to the repo @jkeczan to do this?

**Comment by jkeczan** [comment]
Yes, I am more than willing to have write access. We are actively working on updating the plugin and have it in our roadmap for at least the next year

**Comment by tdm00** [comment]
You've been added as a collaborator, thanks for keeping this alive!

**Comment by jkeczan** [comment]
No Problem. Thanks for trusting me with it!

Jeremy KeczanSoftware Developer
Date: Thu, 30 Apr 2015 06:31:56 -0700

**Pull request merged**
